# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyandSell', '0002_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(default='media/default.jpeg', upload_to=''),
        ),
    ]
