# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyandSell', '0003_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(default='jon.jpg', upload_to=''),
        ),
    ]
