# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-24 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyandSell', '0004_auto_20171002_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='report',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
