# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-28 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyandSell', '0005_item_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(default=b'jon.png', upload_to=b''),
        ),
    ]
